import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://businessinfo.by/")
    page.get_by_role("link", name="Войти").click()
    page.get_by_role("button", name="Дополнительные").click()
    page.get_by_role("link", name="Перейти на сайт ca.").click()
    page.get_by_label("Логин").click()
    page.get_by_label("Логин").click()
    page.get_by_label("Логин").click()
    page.get_by_label("Логин").click()
    page.get_by_label("Логин").click()
    page.get_by_label("Логин").fill("ujKLm6oi")
    page.get_by_label("Пароль").click()
    page.get_by_label("Пароль").fill("gUV-xYZa")
    page.get_by_role("button", name="Войти").click()
    page1 = context.new_page()
    page1.goto("https://businessinfo.by/")
    page.get_by_role("img", name="Показать/скрыть пароль").click()
    page.get_by_role("img", name="Показать/скрыть пароль").click()
    page.get_by_role("button", name="Войти").click()
    page2 = context.new_page()
    page2.goto("https://ca.businessinfo.by/login")
    page.get_by_role("button", name="Войти").click()
    page3 = context.new_page()
    page3.goto("https://ca.businessinfo.by/login")
    page.get_by_role("button", name="Войти").click()
    page4 = context.new_page()
    page4.goto("https://ca.businessinfo.by/login")
    page3.close()
    page4.close()
    page2.close()
    page.get_by_role("button", name="Войти").click()
    page5 = context.new_page()
    page5.goto("https://ca.businessinfo.by/login")
    page5.close()
    page1.get_by_role("link", name="ujKLm6oi Мой профиль").click()
    page1.locator(".menu-btn").click()
    page1.get_by_role("banner").get_by_role("link", name="Новости").click()
    page1.get_by_role("link", name="за неделю").click()
    page1.get_by_role("link", name="за месяц").click()
    page1.get_by_text("Промышленность и производство").click()
    page1.get_by_text("Сельское хозяйство").click()
    page1.get_by_text("Экономика и финансы").click()
    page1.get_by_role("button", name="Найти").click()
    page1.get_by_role("link", name="Подписаться на рассылку").click()
    page1.goto("https://businessinfo.by/news?dateFrom=01.10.2024&dateTo=01.11.2024&partition%5B%5D=3&partition%5B%5D=4&partition%5B%5D=10")
    page1.locator(".menu-btn").click()
    page1.get_by_role("link", name="Справочная информация").click()
    page1.get_by_role("link", name="Настроить напоминания").click()
    page1.goto("https://businessinfo.by/docs/spravochnaya-informatsiya-200083")
    page1.get_by_role("link", name="Базовая величина").click()
    page1.get_by_role("link", name="Календарь кадровика на 2024").click()
    page1.locator(".menu-btn").click()
    page1.get_by_role("link", name="Кодексы").click()
    page1.get_by_role("link", name="Налоговый кодекс Республики Беларусь (Общая часть)").click()
    page1.get_by_role("link", name="Трудовой кодекс Республики Беларусь").click()
    page1.get_by_role("link", name="Банковский кодекс Республики Беларусь").click()
    page1.goto("https://businessinfo.by/docs/bankovskij-kodeks-respubliki-belarus-25-10-2000-33080")
    page1.get_by_role("link", name="Карточка документа").click()
    page1.goto("https://businessinfo.by/docs/card/bankovskij-kodeks-respubliki-belarus-25-10-2000-33080")
    page1.get_by_role("link", name="Текст документа").click()
    page1.get_by_role("link", name="Добавить в избранное").click()
    page1.get_by_role("button", name="Новая папка").click()
    page1.goto("https://businessinfo.by/docs/bankovskij-kodeks-respubliki-belarus-25-10-2000-33080")
    page1.locator("#page-hr").click()
    page1.locator("#page-hr").click()
    with page1.expect_download() as download_info:
        page1.get_by_role("link", name="Скачать в Word").click()
    download = download_info.value
    page1.goto("https://businessinfo.by/docs/bankovskij-kodeks-respubliki-belarus-25-10-2000-33080#")
    page1.get_by_role("link", name="Сравнение редакций").click()
    page1.locator("select[name=\"v2\"]").select_option("20")
    page1.get_by_role("button", name="Сравнить").click()
    page1.locator(".menu-btn").click()
    page1.locator(".menu-btn").click()
    page1.locator(".menu-btn").click()
    page1.locator(".menu-btn").click()
    page1.get_by_role("link", name="Горячие темы").click()
    page1.close()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
