from turtle import *

my_turtle = Turtle()
my_turtle.speed(0)
my_turtle.screen.setup(600, 600)

# тело
my_turtle.penup()
my_turtle.goto(0, -150)
my_turtle.pendown()
my_turtle.fillcolor('#3B7C2E')
my_turtle.begin_fill()
my_turtle.circle(150)
my_turtle.end_fill()

# голова
my_turtle.penup()
my_turtle.goto(0, 0)
my_turtle.pendown()
my_turtle.fillcolor('#3B7C2E')
my_turtle.begin_fill()
my_turtle.circle(100)
my_turtle.end_fill()

# глаза
my_turtle.penup()
my_turtle.goto(-50, 50)
my_turtle.pendown()
my_turtle.fillcolor('white')
my_turtle.begin_fill()
my_turtle.circle(25)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(50, 50)
my_turtle.pendown()
my_turtle.fillcolor('white')
my_turtle.begin_fill()
my_turtle.circle(25)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(-50, 65)
my_turtle.pendown()
my_turtle.fillcolor('black')
my_turtle.begin_fill()
my_turtle.circle(15)
my_turtle.end_fill()

my_turtle.penup()
my_turtle.goto(50, 65)
my_turtle.pendown()
my_turtle.fillcolor('black')
my_turtle.begin_fill()
my_turtle.circle(15)
my_turtle.end_fill()

# нос
my_turtle.penup()
my_turtle.goto(0, 10)
my_turtle.pendown()
my_turtle.fillcolor('#FF7F50')
my_turtle.begin_fill()
my_turtle.circle(20)
my_turtle.end_fill()

# рот
my_turtle.penup()
my_turtle.goto(-30, -30)
my_turtle.pendown()
my_turtle.right(45)
my_turtle.fillcolor('#D2691E')
my_turtle.begin_fill()
my_turtle.forward(60)
my_turtle.right(90)
my_turtle.forward(30)
my_turtle.right(90)
my_turtle.forward(60)
my_turtle.right(135)
my_turtle.forward(80)
my_turtle.end_fill()

# лапы
my_turtle.penup()
my_turtle.goto(-50, -50)
my_turtle.pendown()
my_turtle.pensize(10)
my_turtle.color("#A0522D")

my_turtle.right(20)
my_turtle.forward(70)
my_turtle.right(40)
my_turtle.forward(70)
my_turtle.right(140)
my_turtle.forward(70)
my_turtle.right(40)
my_turtle.forward(70)

my_turtle.penup()
my_turtle.goto(50, -50)
my_turtle.pendown()

my_turtle.left(100)
my_turtle.forward(70)
my_turtle.left(40)
my_turtle.forward(70)
my_turtle.left(140)
my_turtle.forward(70)
my_turtle.left(40)
my_turtle.forward(70)

# завершение рисования
my_turtle.penup()
my_turtle.goto(0, -250)
my_turtle.write("Черепаха закончила свое творение", align="center", font=("Arial", 20, "bold"))
my_turtle.screen.exitonclick()
my_turtle.screen.mainloop()
